-- Ampidirina maina aloha izay rubriques ze zanany farany anarahana an'ilay normes
-- avy eo vo ampidirina izay rubriques meres dia updatena ftsn ze zanany avy eo

-- Classe 1 - Comptes de Capitaux (type_compte = 'Capitaux propres')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Capital, réserves et assimilés', 3),
('Capital', 3),
('Primes liées au capital social', 3),
('Ecart d''évaluation', 3),
('Réserves', 3),
('Ecart d''équivalence', 3),
('Compte de l''exploitant', 3),
('Actionnaires, capital souscrit non appelé', 3),
('Report à nouveau', 3),
('Report à nouveau solde créditeur', 3),
('Report à nouveau solde débiteur', 3),
('Résultat de l''exercice', 3),
('Résultat de l''exercice (bénéfice)', 3),
('Résultat de l''exercice (perte)', 3),
('Produits et charges différés - hors cycle d''exploitation', 3),
('Subventions d''équipement', 3),
('Autres subventions d''investissement', 3),
('Impôts différés actif', 3),
('Impôts différés passif', 3),
('Autres produits et charges différés', 3),
('Disponible', 3),
('Provisions pour charges - passifs non courants', 2),
('Provisions pour pensions et obligations similaires', 2),
('Provisions pour impôts', 2),
('Provisions pour renouvellement des immobilisations', 2),
('Autres provisions pour charges - passifs non courants', 2),
('Emprunts et dettes assimilés', 2),
('Emprunts obligataires convertibles', 2),
('Autres emprunts obligataires', 2),
('Emprunts auprès des établissements de crédit', 2),
('Dépôts et cautionnements reçus', 2),
('Dettes sur contrat de location-financement', 2),
('Autres emprunts et dettes assimilés', 2),
('Primes de remboursement des obligations', 2),
('Dettes rattachées à des participations', 2),
('Dettes rattachées à des participations groupe', 2),
('Dettes rattachées à des participations hors groupe', 2),
('Dettes rattachées à des sociétés en participation', 2),
('Autres dettes rattachées à des participations', 2),
('Comptes de liaison des établissements et sociétés en participation', 2),
('Comptes de liaison entre établissements', 2),
('Comptes de liaison entre sociétés en participation', 2),
('Disponible', 2);

-- Classe 2 - Comptes d'Immobilisations (type_compte = 'Actifs')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Immobilisations incorporelles', 1),
('Frais de développement immobilisables', 1),
('Logiciels informatiques et assimilés', 1),
('Concessions et droits similaires, brevets, licences, marques', 1),
('Fonds commercial', 1),
('Autres immobilisations incorporelles', 1),
('Immobilisations corporelles', 1),
('Terrains', 1),
('Agencements et aménagements de terrain', 1),
('Constructions', 1),
('Installations techniques', 1),
('Autres immobilisations corporelles', 1),
('Immobilisations mises en concession', 1),
('Terrains en concession', 1),
('Agencements et aménagements de terrain en concession', 1),
('Constructions en concession', 1),
('Installations techniques en concession', 1),
('Autres immobilisations corporelles en concession', 1),
('Droits du concédant', 1),
('Immobilisations en cours', 1),
('Immobilisations corporelles en cours', 1),
('Immobilisations incorporelles en cours', 1),
('Avances et acomptes versés sur commandes d''immobilisations', 1),
('Participations et créances rattachées à des participations', 1),
('Titres de participation', 1),
('Autres formes de participations', 1),
('Titres de participation évalués par équivalence', 1),
('Créances rattachées à des participations groupe', 1),
('Créances rattachées à des participations hors groupe', 1),
('Créances rattachées à des sociétés en participation', 1),
('Versements restant à effectuer sur titres de participation non libérés', 1),
('Autres immobilisations financières', 1),
('Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille', 1),
('Titres représentatifs de droit de créance (obligations, bons)', 1),
('Titres immobilisés de l''activité de portefeuille', 1),
('Prêts', 1),
('Dépôts et cautionnements versés', 1),
('Autres créances immobilisées', 1),
('Actions propres (ou parts propres)', 1),
('Versements restant à effectuer sur titres immobilisés non libérés', 1),
('Amortissement des immobilisations', 1),
('Amortissement des immobilisations incorporelles', 1),
('Amortissement des immobilisations corporelles', 1),
('Amortissement des immobilisations mises en concession', 1),
('Perte de valeur sur immobilisations', 1);

-- Classe 3 - Comptes de Stocks et En-Cours (type_compte = 'Actifs')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Matières premières et fournitures', 1),
('Autres approvisionnements', 1),
('Matières consommables', 1),
('Fournitures consommables', 1),
('Emballages', 1),
('En cours de production de biens', 1),
('Produits en cours', 1),
('Travaux en cours', 1),
('En cours de production de services', 1),
('Etudes en cours', 1),
('Prestations de service en cours', 1),
('Stocks de produits', 1),
('Produits intermédiaires', 1),
('Produits finis', 1),
('Produits résiduels ou matières de récupération', 1),
('Stocks de marchandises', 1),
('Stocks à l''extérieur', 1),
('Pertes de valeur sur stocks et en cours', 1),
('Pertes de valeur Matières premières et fournitures', 1),
('Pertes de valeur Autres approvisionnements', 1),
('Pertes de valeur En cours de production de biens', 1),
('Pertes de valeur En cours de production de services', 1),
('Pertes de valeur Stocks de produits', 1),
('Pertes de valeur Stocks de marchandises', 1),
('Pertes de valeur Stocks à l''extérieur', 1);

-- Classe 4 - Comptes de Tiers (type_compte = 'Passifs')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Fournisseurs et comptes rattachés', 2),
('Clients et comptes rattachés', 2),
('Personnel et comptes rattachés', 2),
('Organismes sociaux et comptes rattachés', 2),
('Etat, collectivités publiques, organismes internationaux', 2),
('Groupe et Associés', 2),
('Débiteurs divers et créditeurs divers', 2),
('Comptes transitoires ou d''attente', 2),
('Charges ou produits constatés d''avance et provisions', 2),
('Pertes de valeur sur comptes de tiers', 2);

-- Classe 5 - Comptes Financiers (type_compte = 'Actifs')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Valeurs mobilières de placement', 1),
('Part dans des entreprises liées', 1),
('Banques, établissements financiers et assimilés', 1),
('Instruments de trésorerie', 1),
('Caisse', 1),
('Régies d''avances et accréditifs', 1),
('Pertes de valeur sur comptes financiers', 1);

-- Classe 6 - Comptes de Charges (type_compte = 'Charges')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Achats consommés', 5),
('Services extérieurs', 5),
('Autres services extérieurs', 5),
('Impôts, taxes et versements assimilés', 5),
('Charges de personnel', 5),
('Autres charges des activités ordinaires', 5),
('Charges financières', 5),
('Éléments extraordinaires (charges)', 5),
('Dotations aux amortissements, provisions, pertes de valeur', 5),
('Impôts sur les bénéfices', 5);

-- Classe 7 - Comptes de Produits (type_compte = 'Produits')
INSERT INTO compte_financier (nom, type_compte) VALUES
('Ventes de produits fabriqués, marchandises, prestations', 4),
('Production stockée (ou déstockage)', 4),
('Production immobilisée', 4),
('Subventions d''exploitation', 4),
('Autres produits opérationnels', 4),
('Produits financiers', 4),
('Éléments extraordinaires (produits)', 4),
('Reprises sur provisions et pertes de valeur', 4);
